### ISSUE TITLE
Playlist Cranked out on sidebar

### ISSUE THREAD

**Issue by hapatapa** [pronoy2108/Fluent-Modded-Spotify#10]
![image](https://user-images.githubusercontent.com/68708992/173405084-d3d3695f-38b8-48a0-9438-347ac688131f.png)
Could you remove them so that it looks cleaner?

**Comment by pacman2108** [comment]
@windowz414 I think this is a problem with the css theme/stylesheet(s)

**Comment by hapatapa** [comment]
But is there a way to remove them?

**Comment by pacman2108** [comment]
@hapatapa Yes,
This has been fixed in the latest update of the theme

You can apply it by running the command for installation of the theme

**Comment by pacman2108** [comment]
Fixed in latest version, thus, closed
