### ISSUE TITLE
How to change between dark & light mode ?

### ISSUE THREAD

**Issue by M7MDE7EGAZY** [pronoy2108/Fluent-Modded-Spotify#3]
How to change between dark & light mode ?

**Comment by pacman2108** [comment]
Try this:
https://github.com/pronoy2108/Fluent-Modded-Spotify/releases/download/v2.0/Fluent-Modded-Spotify.Theme.Customizer.html

**Comment by pacman2108** [comment]
Preview:
![image](https://user-images.githubusercontent.com/83197609/147868184-31fe7849-1095-42ac-be55-12d6c729ce26.png)
