### ISSUE TITLE
The activity of friends in the new version does not work (in Pre-release)

### ISSUE THREAD

**Issue by Kotikstar** [pronoy2108/Fluent-Modded-Spotify#6]
The activity of friends in the new version does not work. Only by installing the new version does the activity of friends not work. The buttons in the "Settings" section are not pressed.
![image](https://user-images.githubusercontent.com/52509515/170825181-b07bc609-7bf2-46f8-b534-8afc1668045d.png)

**Comment by pacman2108** [comment]
@Kotikstar, I will try to reproduce this problem when I am free...

**Comment by windowz414** [comment]
Pretty sure that's because of UWP, because Microsoft doesn't like modification of apps we install from their store in place and so likes to restrict users for punishment. I use this on my work PC and it works just perfect; even got scolded by a friend of mine because I just did a little mention of something she recently listened.

**Comment by pacman2108** [comment]
> The activity of friends in the new version does not work. Only by installing the new version does the activity of friends not work. The buttons in the "Settings" section are not pressed. ![image](https://user-images.githubusercontent.com/52509515/170825181-b07bc609-7bf2-46f8-b534-8afc1668045d.png)

I was able to fix the error by updating the theme's source from @williamckha's repo to @flumiie's repo 
(I will create a release for this fix, as soon as possible)

**Comment by pacman2108** [comment]
> The activity of friends in the new version does not work. Only by installing the new version does the activity of friends not work. The buttons in the "Settings" section are not pressed. ![image](https://user-images.githubusercontent.com/52509515/170825181-b07bc609-7bf2-46f8-b534-8afc1668045d.png)

![image](https://user-images.githubusercontent.com/83197609/170831524-7a7c058b-1911-4472-9c8d-5b008ee30d84.png)
<p style="text-align:center;"> Fixed error </p>

Closed
