### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by BobbyESP** [pronoy2108/Fluent-Modded-Spotify#7]
I'm having problems to install the theme. Powershell doesn't recognize the sudo command...

**Comment by pacman2108** [comment]
@BobbyESP This can be fixed by running

scoop install sudo

(If you don't have ```scoop``` installed, you can refer to the instructions in our website or readme.)

**Comment by BobbyESP** [comment]
Thanks! I'll try to install it later!

**Comment by windowz414** [comment]
@pronoy2108, I'm sure we can implement something that doesn't depend on `sudo` for Windows. I can also help after 2 weeks if needed.
